[package]
# name = "katei/ruby"
name = "Michael-F-Bryan/ruby"
version = "0.1.2"
description = "The Ruby Programming Language"
license = "MIT"
repository = "https://github.com/ruby/ruby.wasm"

[[module]]
name = "ruby-cli"
source = "dist/ruby.wasm"
abi = "wasi"

[[module]]
name = "ruby"
source = "dist/libruby.wasm"
abi = "wasi"
bindings = { wit-exports = "dist/rb-abi-guest.wit", wit-bindgen = "0.1.0" }

[[command]]
name = "ruby"
module = "ruby-cli"
